### ISSUE TITLE
Skip local plugin?

### ISSUE THREAD

**Issue by Bluefitdev** [wsdjeg/SpaceVim#3577] opened 2020-06-16 07:01 UTC
Hey there,

I just installed space vim from vscode, seems like there are plenty of things to learn. Very excited but I can't seem to get stuff to work. I'm not sure if this is a bug:

<img width="2342" alt="Screen Shot 2020-06-16 at 4 58 53 pm" src="https://user-images.githubusercontent.com/56941349/84741782-e8bf0280-aff2-11ea-8de4-11fc729f1a0f.png">

But my plugins kept waiting at `Skip Local`, denite won't work after that.

This happens both at nvim and vim 

Denite produces this error:
```
[denite] Vim(let):E117: Unknown function: yarp#py3
[denite] function <SNR>30_warp_denite[1]..denite#helper#call_denite[7]..denite#start[4]..<SNR>194_start[1]..denite#initialize[1]..denite#init#_initialize, line 28
Error detected while processing function <SNR>30_warp_denite[1]..denite#helper#call_denite[7]..denite#start[4]..<SNR>194_start[1]..denite#initialize[1]..denite#init#_initialize[43]..denite#init#_msgpack_version_check:
line    5:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'msgpack'
```

I can confirm that I have python3 installed in both nvim and vim (on mac, but I used vim 8.2 custom install)

Please help

Thanks

**Comment by Shougo** [comment] 2020-06-16 07:41
You need to install msgpack module by pip3

**Comment by vperilla** [comment] 2020-06-16 16:09
Same here, and I have msgpack installed..

[Video](https://asciinema.org/a/340160)

**Comment by Bluefitdev** [comment] 2020-06-16 23:08
It was installed.. doesn't work. I had to uninstall spacevim then reinstall it again to work

Edit: Kept happening though when I tried to change layers or install stuff

**Comment by vperilla** [comment] 2020-06-16 23:14
> It was installed.. doesn't work. I had to uninstall spacevim then reinstall it again to work
> 
> Edit: Kept happening though when I tried to change layers or install stuff
The same here

**Comment by Bluefitdev** [comment] 2020-06-16 23:34
<img width="582" alt="Screen Shot 2020-06-17 at 9 32 31 am" src="https://user-images.githubusercontent.com/56941349/84838348-865f1400-b07d-11ea-9b47-fe108fd7a6b0.png">

Stuck again everytime I need to install something

Any chance we can change the plugin manager to something else? I started to like spacevim but this is getting in my way I really can't work

**Comment by Bluefitdev** [comment] 2020-06-16 23:41
I just realise, if I used the installation procedure from the home page, it points me to SpaceVim v1.5 which is buggy, just download the released 1.4 then you should be fine.. I think its working now

**Comment by Shougo** [comment] 2020-06-17 00:16
> [denite] Vim(let):E117: Unknown function: yarp#py3

You need to install `nvim-yarp` plugin.

**Comment by Shougo** [comment] 2020-06-17 00:19
https://github.com/Shougo/deoplete.nvim/issues/1077#issuecomment-595665114

In the first, you need to uninstall old msgpack package(`python-msgpack`).
And please update `msgpack` by pip3.

`python3 -mpip install --user -U msgpack`

**Comment by Shougo** [comment] 2020-06-17 00:22
@vperilla

> Same here, and I have msgpack installed..

Please see the video.
You use pyenv for pip.  But neovim does not use the pyenv python.
You can check it by `:checkhealth`.

**Comment by Bluefitdev** [comment] 2020-06-17 01:32
Thanks for your reply.. However right now somehow its just working after I moved to spacevim 1.4 with neovim

My normal vim (installed with brew) can't seem to detect msgpack however I reinstall it. Probably because my `PYTHON3_HOST_PROG` is pointed to anaconda. Not sure though

**Comment by Shougo** [comment] 2020-06-17 02:14
Hm.  I don't know the reason.  But you can execute `:checkhealth` for it.

**Comment by vperilla** [comment] 2020-06-17 20:18
> @vperilla
> 
> > Same here, and I have msgpack installed..
> 
> Please see the video.
> You use pyenv for pip. But neovim does not use the pyenv python.
> You can check it by `:checkhealth`.
@Shougo 
https://asciinema.org/a/340555

Issue occurs when I run SPUpdate

**Comment by Shougo** [comment] 2020-06-17 22:40
> You use pyenv for pip. But neovim does not use the pyenv python.
> You can check it by :checkhealth.

Please read this comment.

**Comment by FanFani4** [comment] 2020-06-18 07:14
had same issue after SPUpdate - fixed by 

cd ~/.vim
git restore .

**Comment by lmascelli** [comment] 2020-06-18 07:24
i had the same issue with gvim and 1.5-dev and msgpack module installed.
gvim and 1.4 works fine.

**Comment by lmascelli** [comment] 2020-06-18 07:31
> 
> 
> had same issue after SPUpdate - fixed by
> 
> cd ~/.vim
> git restore .

Does the packages update correctly after restoring or simply the package manager doesn't show up at startup? For me the second one.

**Comment by Shougo** [comment] 2020-06-18 07:38
It maybe related.
Please read the issue.

https://github.com/roxma/vim-hug-neovim-rpc/issues/47

**Comment by wsdjeg** [comment] 2020-06-18 15:15
Skip local plugin means this plugin is not git repo, it is local plugin, in SpaceVim, we merge all default plugin into [bundle](https://github.com/SpaceVim/SpaceVim/tree/master/bundle) directory, so all of these plugin do not need to be updated. this feature will make SpaceVim out of box and easy to installed with out git or network.

**Closed as completed by wsdjeg** 2020-06-18 15:15 UTC

**Comment by robertwt7** [comment] 2020-06-18 21:49
But that’s nerdtree... and it goes for gruvbox as well. Also it works fine after we switched back to 1.4

**Comment by ChasingZenith** [comment] 2020-06-19 07:45
I had the same issue. 
Every time I opened vim and neovim the plugin updater showed up

```
clever-f               skip local
editorconfig-vim       skip local
intendLine             skip local
gruvbox                skip local
```

If I open a file, it would tell me that 'gruvbox' is not yet installed. The colorscheme was quite ugly.
Inspired by 
https://github.com/SpaceVim/SpaceVim/issues/3577#issuecomment-645827451

I ran `git status`, and I found something strange. Multiple folders are missed in the folder bundle.

```bash
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    bundle/clever-f.vim/.codecov.yml
	deleted:    bundle/clever-f.vim/.github/workflows/ci.yml
	deleted:    bundle/clever-f.vim/.gitignore
	deleted:    bundle/clever-f.vim/README.md
	deleted:    bundle/clever-f.vim/autoload/clever_f.vim
	deleted:    bundle/clever-f.vim/autoload/clever_f/compat.vim
	deleted:    bundle/clever-f.vim/autoload/clever_f/migemo/cp932.vim
	deleted:    bundle/clever-f.vim/autoload/clever_f/migemo/eucjp.vim
	deleted:    bundle/clever-f.vim/autoload/clever_f/migemo/utf8.vim
	deleted:    bundle/clever-f.vim/doc/clever_f.txt
	deleted:    bundle/clever-f.vim/plugin/clever-f.vim
	deleted:    bundle/clever-f.vim/test/.coveragerc
	deleted:    bundle/clever-f.vim/test/.themisrc
	deleted:    bundle/clever-f.vim/test/README.md
	deleted:    bundle/clever-f.vim/test/test.vimspec
	deleted:    bundle/editorconfig-vim/.appveyor.yml
	deleted:    bundle/editorconfig-vim/.editorconfig
	deleted:    bundle/editorconfig-vim/.gitignore
	deleted:    bundle/editorconfig-vim/.gitmodules
	deleted:    bundle/editorconfig-vim/.travis.yml
	deleted:    bundle/editorconfig-vim/CONTRIBUTORS
	deleted:    bundle/editorconfig-vim/LICENSE
	deleted:    bundle/editorconfig-vim/LICENSE.PSF
	deleted:    bundle/editorconfig-vim/README.md
	deleted:    bundle/editorconfig-vim/autoload/editorconfig.vim
	deleted:    bundle/editorconfig-vim/autoload/editorconfig_core.vim
	deleted:    bundle/editorconfig-vim/autoload/editorconfig_core/fnmatch.vim
	deleted:    bundle/editorconfig-vim/autoload/editorconfig_core/handler.vim
	deleted:    bundle/editorconfig-vim/autoload/editorconfig_core/ini.vim
	deleted:    bundle/editorconfig-vim/autoload/editorconfig_core/util.vim
	deleted:    bundle/editorconfig-vim/doc/editorconfig.txt
	deleted:    bundle/editorconfig-vim/mkzip.sh
	deleted:    bundle/editorconfig-vim/plugin/editorconfig.vim
	deleted:    bundle/editorconfig-vim/tests/core/CMakeLists.txt
	deleted:    bundle/editorconfig-vim/tests/core/CTestCustom.cmake
	deleted:    bundle/editorconfig-vim/tests/core/ecvbslib.vbs
	deleted:    bundle/editorconfig-vim/tests/core/ecvimlib.ps1
	deleted:    bundle/editorconfig-vim/tests/core/editorconfig
	deleted:    bundle/editorconfig-vim/tests/core/editorconfig.bat
	deleted:    bundle/editorconfig-vim/tests/core/editorconfig1.vbs
	deleted:    bundle/editorconfig-vim/tests/core/editorconfig2.ps1
	deleted:    bundle/editorconfig-vim/tests/fetch-vim.bat
	deleted:    bundle/editorconfig-vim/tests/fetch-vim.sh
	deleted:    bundle/editorconfig-vim/tests/plugin/.gitignore
	deleted:    bundle/editorconfig-vim/tests/plugin/Gemfile
	deleted:    bundle/editorconfig-vim/tests/plugin/Gemfile.lock
	deleted:    bundle/editorconfig-vim/tests/plugin/Rakefile
	deleted:    bundle/editorconfig-vim/tests/plugin/spec/.editorconfig
	deleted:    bundle/editorconfig-vim/tests/plugin/spec/editorconfig_spec.rb
	deleted:    bundle/editorconfig-vim/tests/travis-test.sh
	deleted:    bundle/gruvbox/CHANGELOG.md
	deleted:    bundle/gruvbox/README.md
	deleted:    bundle/gruvbox/autoload/airline/themes/gruvbox.vim
	deleted:    bundle/gruvbox/autoload/gruvbox.vim
	deleted:    bundle/gruvbox/autoload/lightline/colorscheme/gruvbox.vim
	deleted:    bundle/gruvbox/colors/gruvbox.vim
	deleted:    bundle/gruvbox/gruvbox_256palette.sh
	deleted:    bundle/gruvbox/gruvbox_256palette_osx.sh
	deleted:    bundle/gruvbox/package.json
	deleted:    bundle/indentLine/.gitignore
	deleted:    bundle/indentLine/LICENSE
	deleted:    bundle/indentLine/README.md
	deleted:    bundle/indentLine/after/plugin/indentLine.vim
	deleted:    bundle/indentLine/after/syntax/indentLine.vim
	deleted:    bundle/indentLine/doc/indentLine.txt
	deleted:    bundle/indentLine/glyph/indentLine-dotted-guide.eps

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	UltiSnips/
	after/syntax/tex/
	ftplugin/tex/
	strange.log

no changes added to commit (use "git add" and/or "git commit -a")
```

This is kind of consistent with what [wsdjeg](https://github.com/SpaceVim/SpaceVim/issues/3577#issuecomment-646087288) https://github.com/SpaceVim/SpaceVim/issues/3577#issuecomment-646087288 said.


> Skip local plugin means this plugin is not git repo, it is local plugin, in SpaceVim, we merge all default plugin into [bundle](https://github.com/SpaceVim/SpaceVim/tree/master/bundle) directory, so all of these plugin do not need to be updated. this feature will make SpaceVim out of box and easy to installed with out git or network.


As I want to keep the configuration that I added in other folders, I went to path `~/.vim/bundle` instead of `~/.vim/` and ran `git restore .`, i.e.,
I run
```
cd ~/.vim/bundle
git restore .
```

After that everything went well.

**Comment by lmascelli** [comment] 2020-06-20 09:06
what i noticed is that calling the SPUdate command delete some of the bundle folders

and like @ChasingZenith said

```
cd ~/.vim/bundle
git restore .
```

solve the problem... until the next SPUpdate.

**Comment by latteye** [comment] 2020-06-23 00:07
I can confirm that I encountered same problem and resolved by install from 1.4.0 release package.

**Comment by AllenDang** [comment] 2020-07-09 04:13
Why this issue is closed? It happens again and again after SPUpdate.

**Comment by Shougo** [comment] 2020-07-09 04:17
You need to install SpaceVim latest version.

**Comment by latteye** [comment] 2020-07-12 03:02
> 
> 
> You need to install SpaceVim latest version.

Just want to confirm , the "latest" you mean is latest commit in master branch , not the latest release , right ?

**Comment by Shougo** [comment] 2020-07-12 03:35
Yes.

**Comment by latteye** [comment] 2020-07-12 11:37
![image](https://user-images.githubusercontent.com/2050086/87245318-0f981980-c477-11ea-8024-61be76b93136.png)

I think the issue still there.

**Comment by Shougo** [comment] 2020-07-12 12:50
> I think the issue still there.

Ah, I get it.  This is intended behavior.
The old problem is if you update plugins, it breaks current plugins.  But the problem is fixed.

The `Skip local` means SpaceVim includes built-in plugins(for example: vimfiler) and it cannot be updated by users.
It is @wsdjeg 's decision.

**Comment by latteye** [comment] 2020-07-13 02:39
Thank you for the explanation .

**Comment by Tokubara** [comment] 2021-12-30 09:42
So how to update local plugins? `dein` has a bug, the latest version has fixed it. How can I update `dein`?

**Comment by Tokubara** [comment] 2021-12-30 09:46
I find that local plugin's(`dein`) github upstream is `https://github.com/SpaceVim/SpaceVim.git`, but it has a bug and should be pulled.

**Comment by wsdjeg** [comment] 2021-12-31 01:33
I will update the dein, thanks.
