### ISSUE TITLE
Error detected while processing function SpaceVim#plugins#flygrep#open

### ISSUE THREAD

**Issue by krnr** [wsdjeg/SpaceVim#4075] opened 2021-02-06 10:31 UTC
## Expected behavior, english is required

after selecting on of the flygrep results, window is opened with the cursor at the place where the text was found.

## The reproduce ways from Vim starting (Required!)

Hit `SPC s /`, select the result and you'll first see:

```
Error detected while processing function SpaceVim#plugins#flygrep#open[77]..251[8]..254[15]..<SNR>234_open_item:
line   19:
```

and then after hitting Enter, the file is open from the last place you was in it, cursor is gone. updating spacevim doesn't help.

## Debug info

```
SpaceVim layers:

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
- foldsearch:           not loaded          https://spacevim.org/layers/foldsearch/
+ format:                   loaded          https://spacevim.org/layers/format/
- fuzzy:                not loaded          no exists
+ fzf:                      loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- gtags:                not loaded          https://spacevim.org/layers/gtags/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#actionscript:    not loaded          https://spacevim.org/layers/lang/actionscript/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#aspectj:         not loaded          https://spacevim.org/layers/lang/aspectj/
- lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
- lang#c:               not loaded          https://spacevim.org/layers/lang/c/
- lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#d:               not loaded          https://spacevim.org/layers/lang/d/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#eiffel:          not loaded          https://spacevim.org/layers/lang/eiffel/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#factor:          not loaded          no exists
- lang#forth:           not loaded          no exists
- lang#fortran:         not loaded          https://spacevim.org/layers/lang/fortran/
- lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
- lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
- lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
- lang#html:            not loaded          https://spacevim.org/layers/lang/html/
- lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
- lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
- lang#io:              not loaded          https://spacevim.org/layers/lang/io/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#j:               not loaded          https://spacevim.org/layers/lang/j/
- lang#janet:           not loaded          https://spacevim.org/layers/lang/janet/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#lasso:           not loaded          https://spacevim.org/layers/lang/lasso/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
- lang#markdown:        not loaded          https://spacevim.org/layers/lang/markdown/
- lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
- lang#moonscript:      not loaded          https://spacevim.org/layers/lang/moonscript/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
- lang#pascal:          not loaded          https://spacevim.org/layers/lang/pascal/
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
- lang#povray:          not loaded          https://spacevim.org/layers/lang/povray/
- lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
+ lang#python:              loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#ring:            not loaded          https://spacevim.org/layers/lang/ring/
- lang#rst:             not loaded          https://spacevim.org/layers/lang/rst/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          https://spacevim.org/layers/lang/slim/
- lang#sml:             not loaded          https://spacevim.org/layers/lang/sml/
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#supercollider:   not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
- lang#toml:            not loaded          https://spacevim.org/layers/lang/toml/
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
- lang#v:               not loaded          https://spacevim.org/layers/lang/v/
- lang#vbnet:           not loaded          https://spacevim.org/layers/lang/vbnet/
- lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#wdl:             not loaded          no exists
- lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
- lang#xml:             not loaded          https://spacevim.org/layers/lang/xml/
- lang#xquery:          not loaded          no exists
- lang#zig:             not loaded          https://spacevim.org/layers/lang/zig/
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          https://spacevim.org/layers/language-server-protocol/
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
- sudo:                 not loaded          https://spacevim.org/layers/sudo/
- test:                 not loaded          https://spacevim.org/layers/test/
- tmux:                 not loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          https://spacevim.org/layers/tools/mpv/
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- vim:                  not loaded          no exists
```

## Screenshots

![Screenshot_2021-02-06_13-26-40](https://user-images.githubusercontent.com/8479133/107115661-3983b400-687f-11eb-95ca-12d83c6109bc.png)

![Screenshot_2021-02-06_13-27-47](https://user-images.githubusercontent.com/8479133/107115663-3d173b00-687f-11eb-879c-fa3516bbb495.png)

**Comment by wsdjeg** [comment] 2021-02-10 03:00
What is the full error message?

**Comment by wsdjeg** [comment] 2021-02-10 03:09
I can not reproduce it. the line 19 is only to call the function `cursor()`, `call cursor(liner, colum)`, it should not cause E474

**Comment by krnr** [comment] 2021-02-10 08:47
> What is the full error message?

```
Error detected while processing function SpaceVim#plugins#flygrep#open[77]..251[8]..254[15]..<SNR>234_open_item:
line   19:
E474: Invalid argument


Error detected while processing function SpaceVim#plugins#flygrep#open[77]..264[8]..267[15]..<SNR>234_open_item:
line   19:
E474: Invalid argument

```

so figures after .. can change.

**Comment by wsdjeg** [comment] 2021-02-10 09:46
what is the version of your vim

**Comment by krnr** [comment] 2021-02-10 12:09
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 18:17:04)
Included patches: 1-2347
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lacl -lattr -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm 
```

**Comment by wsdjeg** [comment] 2021-02-10 14:11
I still can not reproduce it, does your spacevim udpate to latest version? and what is the result of `git -C ~/.SpaceVim status`

**Comment by krnr** [comment] 2021-02-13 04:54
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

reinstall of vim doesn't help, but what i've noticed, that after that error i also lose the cursor in the terminal:
![image](https://user-images.githubusercontent.com/8479133/107841946-91b33c80-6dd0-11eb-9e7b-c231eaaa0e66.png)

normally it must look like
![image](https://user-images.githubusercontent.com/8479133/107841953-9f68c200-6dd0-11eb-8981-74203eea3843.png)

i don't know whether it will help to lead to the conclusion

**Comment by wsdjeg** [comment] 2021-02-13 15:21
we need help with this issue, because I can not reproduce it.

**Comment by Midren** [comment] 2021-02-19 12:38
I have the same issue with FlyGrep, but without SpaceVim
```
Error detected while processing function FlyGrep#open[1]..SpaceVim#plugins#flygrep#open[77]..281[8]..284[15]..<SNR>161_open_item:
line   19:
E474: Invalid argument
```

**Comment by wsdjeg** [comment] 2021-02-20 14:38
But I can not reproduce it, the open item function is:

```
function! s:open_item() abort
  let s:MPT._handle_fly = function('s:flygrep')
  if getline('.') !=# ''
    if s:grepid != 0
      call s:JOB.stop(s:grepid)
    endif
    call s:MPT._clear_prompt()
    let s:MPT._quit = 1
    let line = getline('.')
    let filename = fnameescape(split(line, ':\d\+:')[0])
    let linenr = matchstr(line, ':\d\+:')[1:-2]
    let colum = matchstr(line, '\(:\d\+\)\@<=:\d\+:')[1:-2]
    if s:preview_able == 1
      call s:close_preview_win()
    endif
    let s:preview_able = 0
    noautocmd q
    exe 'silent e ' . filename
    call s:update_history()
    call cursor(linenr, colum)
    noautocmd normal! :
  endif
endfunction
```

and the line 19 is only:

```
    call cursor(linenr, colum)

```

I do not know why it causes `E474: Invalid argument`

**Comment by Midren** [comment] 2021-02-21 17:15
@krnr, I was able to fix issue by changing `cursor(linenr, column)` to `exe 'call cursor(' . linenr ', ' . colum ')'`. I'm not sure, what is the origin of the problem, but at least it fixes )

**Comment by krnr** [comment] 2021-02-22 06:13
> exe 'call cursor(' . linenr ', ' . colum ')'

it actually works! thank you.

**Comment by wsdjeg** [comment] 2021-02-27 13:23
THis issue has been fixed, please update SpaceVim.

**Comment by Midren** [comment] 2021-02-27 15:13
@wsdjeg this fixes issue, when only opening in a new tab. The same changes should be applied in `s:open_item`, `s:open_item_vertically`, `s:open_item_horizontally` functions

**Comment by wsdjeg** [comment] 2021-02-28 02:13
OK.

**Comment by wsdjeg** [comment] 2021-02-28 04:59
fixed in https://github.com/SpaceVim/SpaceVim/pull/4115

**Closed as completed** 2021-02-28 05:10 UTC
Labels: help wanted, can-not-reproduce
