### ISSUE TITLE
SPC-f-f/SPC-p-f bindings always say "NO ENTRIES"

### ISSUE THREAD

**Issue by reem** [wsdjeg/SpaceVim#516] opened 2017-05-11 21:56 UTC
## Expected behavior, english is recommend

The files in the current directory/project respectively are listed.

## Environment Information
- OS: macOS 10.12
- vim version: 8.0
- neovim version: 0.2.0

## The reproduce ways from Vim starting (Required!)

Just open any file in this repo (e.g. README.md) and try SPC-f-f or SPC-p-f.

## Output of the ':SPDebugInfo!'

Same as in https://github.com/SpaceVim/SpaceVim/issues/515

## Screenshots

Here's an asciinema recording of the issue using this repository as an example: https://asciinema.org/a/3hevp4ew9o7md1twl8dmjsuij

**Comment by wsdjeg** [comment] 2017-05-12 11:46
I can not reproduce it,.

https://asciinema.org/a/7a1qj8d3dizxjus95zfyq61x0

**Comment by wsdjeg** [comment] 2017-05-12 11:48
ok. I got it, your vim has no python support,  you should use recompile your vim.

**Comment by wsdjeg** [comment] 2017-05-12 11:48
will fix it

**Comment by wsdjeg** [comment] 2017-05-12 11:52
It in config of ctrlp
```vim
if !exists('g:ctrlp_match_func') && (has('python') || has('python3'))
  let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch'  }
endif
```
so, I think SpaceVim has no bugs, if your vim do not support py, the pymatch will not be loaded, so It should not be `NO ENTRIES`.

**Comment by wsdjeg** [comment] 2017-05-15 12:34
I can not reproduce in old vim:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 15 2017 19:38:26)
Included patches: 1
Compiled by wsdjeg
Huge version with GTK2 GUI.  Features included (+) or not (-):
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    
+farsi           +mouse_netterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/local/include  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lXt -lX11 -lSM -lICE  -lm -lncurses -lacl -lgpm -ldl
```

**Comment by jetm** [comment] 2017-05-15 13:34
@wsdjeg: I can reproduce this:

https://asciinema.org/a/8nj8vf7qns0eliepjpstohhkd

I expect to see the files in the current directory after run SPC-f-f.

These are all information I could gather. Am I missing something else, like configuration settings? 

- OS: Arch Linux
- vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 26 2017 07:49:10)
Included patches: 1-586
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     
```

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 3
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'onedark'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['sheerun/vim-polyglot', {'merged': 0}], ['vitalk/vim-shebang'], ['octol/vim-cpp-enhanced-highlight', {'on_ft': 'c'}], ['igankevich/mesonic'], ['benmills/vimux']]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 0
g:spacevim_max_column = 80
g:spacevim_enable_debug = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'ycm'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 1
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'vim', 'linux', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/javier/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_leader_guide_vertical = 0
g:spacevim_realtime_leader_guide = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 1
g:spacevim_debug_level = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
```


### SpaceVim Health checking:

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /home/javier/.cache/SpaceVim/SpaceVim.log does not exists, only log for current process will be shown!
```
SpaceVim configuration:
```viml
" Here are some basic customizations, please refer to the
" ~/.SpaceVim.d/init.vim

"
" SpaceVim settings:
"

" If you want to add some custom plugins, use these options:
let g:spacevim_custom_plugins = [
  \ ['sheerun/vim-polyglot', {'merged' : 0}],
  \ ['vitalk/vim-shebang'],
  \ ['octol/vim-cpp-enhanced-highlight', {'on_ft':'c'}],
  \ ['igankevich/mesonic'],
  \ ['benmills/vimux'],
  \ ]

" Disable plugins
let g:spacevim_disabled_plugins = [
  \ ]

" file for all possible options:
let g:spacevim_default_indent = 3
let g:spacevim_max_column     = 80

if has("gui_running")
  let g:spacevim_guifont = 'Input\ Mono\ Narrow\ Semi-Condensed\ 11'
end

" Set Atom colorscheme
let g:spacevim_colorscheme = 'onedark'

" Disable vimfile in welcome window
let g:spacevim_enable_vimfiler_welcome = 0

" Enable lint on the fly
let g:spacevim_lint_on_the_fly = 1

"
" YouCompleteMe plugin settings
"

" Enable YCM in SpaceVim
let g:spacevim_enable_ycm = 1

" Diagnostics error symbol
let g:ycm_error_symbol = '✗'

" Diagnostics warning symbol
let g:ycm_warning_symbol = '⚠'

" Force the use of Python 3 interpreter for ycmd. YCM is built for Python 3
let g:ycm_python_binary_path = '/usr/bin/python3'

"
" nerd-commenter plugin settings
"
" Add extra space around delimiters when commenting, remove them when
" uncommenting
let g:NERDSpaceDelims = 1

" Always remove the extra spaces when uncommenting regardless of whether
" NERDSpaceDelims is set
let g:NERDRemoveExtraSpaces = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of the following code
" indentation
let g:NERDDefaultAlign = 'left'

" Allow commenting and inverting empty lines (useful when commenting a
" region)
let g:NERDCommentEmptyLines = 1

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Always use alternative delimiter
let g:NERD_c_alt_style = 1
let g:NERDCustomDelimiters = {'c': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' }}

"
" Syntastic plugin settings
"
" Load Syntatic
"let g:spacevim_enable_neomake = 0

" Diagnostics error symbol
"let g:syntastic_error_symbol = '✗'

" Diagnostics warning symbol
"let g:syntastic_warning_symbol = '⚠'

"
" Code Formatting
"
" Configure clang-format
let g:neoformat_c_clangformat = {
    \ 'exe': 'clang-format',
    \ 'args': ['-style=file'],
    \ 'stdin': 1,
    \ 'no_append': 1,
    \ }

let g:neoformat_enabled_c = ['clangformat']

"
" Misc
"

" vim:tw=78:ts=2:sw=2
```

**Comment by wsdjeg** [comment] 2017-05-15 14:03
@jetm how about press `F5` in ctrlp buffer?

**Comment by jetm** [comment] 2017-05-15 15:20
@wsdjeg: `F5` in CtrlP buffer has not effect. Also, I ran `:CtrlPClearCache`, according to the documentation is the same than `F5`. Ran `CtrlP: /home/javier` to look for all files in my home directory and nothing. Is there a logging file I should be looking for errors or something like this?

**Comment by wsdjeg** [comment] 2017-05-15 15:28
try remove 
```vim
if !exists('g:ctrlp_match_func') && (has('python') || has('python3'))
  let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch'  }
endif
```
in https://github.com/SpaceVim/SpaceVim/blob/dev/config/plugins/ctrlp.vim to see if it works?

**Comment by jetm** [comment] 2017-05-15 16:28
@wsdjeg: I use `rg`, instead of `ag`. So I tracked the problem in how the exclude globals are produced. With that pull request, it solves my problem. It might solve this issue as well.

**Comment by wsdjeg** [comment] 2017-05-15 22:45
merged, thanks.

**Comment by jetm** [comment] 2017-05-25 00:44
@wsdjeg: I want to help in fixing this. I was near to fix it because I could get the list of files, but my PR #538 broke denite config. How can I test denite config to know my next PR will not break denite config?

**Comment by wsdjeg** [comment] 2017-05-25 12:56
I think it is due to the command of ctrlp is broken, can you post your : g:ctrlp_user_command?
in my config it is 
```
rg %s --no-ignore --hidden --files -g "" -g !*/tmp/* -g !*.so -g !*.swp -g !*.zip -g !*.class -g !tags -g !*.jpg -g !*.ttf -g !*.TTF -g !*.png -g !*/target/* -g !.git -g !.svn -g !.hg -g !.DS_Store -g !*.svg
```

**Comment by jetm** [comment] 2017-05-25 23:06
Mine is this:
```vim
let g:ctrlp_user_command = "rg %s --no-ignore --hidden --files -g '' -g '!*/tmp/*' -g '!*.so' -g '!*.swp' -g '!*.zip' -g !'*.class' -g '!tags' -g '!*.jpg' -g '!*.ttf' -g '!*.TTF' -g '!*.png' -g '!*/target/*' -g '!.git' -g '!.svn' -g '!.hg' -g '!.DS_Store' -g '!*.svg'"
```

**Comment by wsdjeg** [comment] 2017-05-25 23:25
it is wrong. I think you should use let@+=g:ctrlp_user_command. and copy to here

**Comment by jetm** [comment] 2017-05-26 00:29
OK. Running in Vim `:let let g:ctrlp_user_command` produce this:

```vim
g:ctrlp_user_command   rg %s --no-ignore --hidden --files -g "" -g !*/tmp/* -g !*.so -g !*.swp -g !*.zip -g !*.class -g !tags -g !*.jpg -g !*.ttf -g !*.TTF -g !*.png -g !*/target/* -g !.git -g !.svn -g !.hg -g !.DS_Store -g !*.svg
```

But, in my last PR #538 I modified SpaceVim, to produce this output:

```vim
g:ctrlp_user_command   rg %s --no-ignore --hidden --files -g "" -g '!*/tmp/*' -g '!*.so' -g '!*.swp' -g '!*.zip' -g '!*.class' -g '!tags' -g '!*.jpg' -g '!*.ttf' -g '!*.TTF' -g '!*.png' -g '!*/target/*' -g '!.git' -g '!.svn' -g '!.hg' -g '!.DS_Store' -g '!*.svg'
```
That fix my issue. Note the single quote between the pattern. `rg` man page says it should use like this, between single quotes.
What am I trying to understand is how that could break Denite?

**Comment by wsdjeg** [comment] 2017-05-26 00:35
denite use list as command, each item will be auto surrounded by quote. hmm, will look in to it.

**Closed as completed** 2017-05-29 23:43 UTC

**Comment by ChenXiyu** [comment] 2017-07-11 10:05
Hi, 
I still have the same issues, and can't abstract the solution from the discussions happened above.
I tried latest version of NeoVim(v0.2.0) and Vim v8.0, installed python3 and ran command `pip3 install neovim`
also, i tried remove the Ctrlp configurations which mentioned by you, still have got no entries.
can anyone explain the root causes of this issue? and any solutions?

**Comment by wsdjeg** [comment] 2017-07-11 13:01
New issue will b better.

**Comment by ChenXiyu** [comment] 2017-07-12 01:24
Thanks, I got one solution from CtrlP project: write `set shell=/bin/bash` to your customize config, this works for me.
